// Nomo Clipper —— 中文文案集中存放，便于未来 i18n

export const T = {
  // popup
  loading: '正在提取页面内容…',
  restrictedPage: '当前页面无法剪藏（如浏览器内置页、扩展商店、PDF 等）',
  fieldContent: '正文',
  fieldFolder: '保存文件夹',
  fieldFilename: '文件名',
  fieldVault: '目标仓库',
  saveLocation: '保存位置',
  saveTo: '保存到',
  filenameNote: '磁盘上的 .md 文件名，默认同标题（改这里不影响笔记标题）',
  properties: '属性',
  useSelection: '使用选中文字',
  useFullArticle: '使用整页正文',
  fullCapture: '完整抓取全文',
  fullCapturing: '正在滚动加载全文…',
  fullCaptureHint: '页面会自动滚动一遍，请勿操作',
  highlightsCount: (n: number) => `本页高亮 ${n} 条`,
  highlightTool: '高亮工具',
  highlightFloatingToggle: '划词浮动按钮',
  highlightShortcutHint: '快捷键：⌘/Ctrl+Shift+Y，也可选中文字后右键高亮',
  insertHighlights: '插入到正文',
  clearHighlights: '清除',
  wordCount: (n: number) => `约 ${n} 字`,
  save: '保存到 Obsidian',
  saveFeishu: '保存到飞书知识库',
  saving: '正在保存…',
  savedOk: '已保存',
  savedPartial: '已部分保存',
  savedAsCopy: (filename: string) => `已另存为 ${filename}.md`,
  openInObsidian: '在 Obsidian 打开',
  openInFeishu: '在飞书打开',
  closeWindow: '关闭',
  // popup —— 飞书保存
  feishuNeedApp: '请先在设置里填写飞书 App ID / App Secret',
  feishuNeedSpace: '请先在设置里选择目标知识库',
  feishuImageHint: '飞书保存会先把正文导入为飞书文档；公开图片通常由飞书导入器解析，需登录图片可能无法被飞书服务器读取。',
  feishuDest: '飞书保存位置',
  feishuDestHint: '保存为飞书文档并放入上面所选知识库位置（在设置里可改）。',
  feishuImages: (saved: number, total: number) => `图片 ${saved}/${total} 已交给飞书导入器处理`,
  propLabels: {
    source: '来源',
    author: '作者',
    published: '发布日期',
    modified: '修改日期',
    created: '创建日期',
    description: '描述',
  },
  existsWarn: '仓库已有同名笔记，保存时需要选择处理方式',
  conflictTitle: '发现同名笔记',
  conflictHint: '请选择覆盖原笔记、另存为自动编号的副本，或取消本次保存。',
  conflictOverwrite: '覆盖更新',
  conflictCopy: '另存副本',
  conflictCancel: '取消',
  draftFound: '发现这个页面上次未保存的草稿',
  draftRestore: '恢复草稿',
  draftDiscard: '丢弃草稿',
  draftRestored: '已恢复上次未保存的草稿',
  draftDiscarded: '已丢弃旧草稿，使用本次新抓取内容',
  draftChooseFirst: '请先恢复或丢弃上次未保存的草稿',
  biliTimestamp: '记录当前时间点',
  biliTimestamping: '正在读取时间…',
  biliTimestampAdded: (label: string) => `已记录 B站时间点 ${label}`,
  douyinTranscript: '转录抖音字幕',
  douyinTranscribing: '正在识别字幕…',
  douyinConnecting: '正在自动启动本地字幕助手…',
  douyinTranscribingHint: '正在下载音频并进行本地语音识别…',
  douyinTranscriptHint: '自动唤醒本机 Whisper 识别当前抖音视频，不上传转录云端',
  douyinKeepOpen: '首次会下载模型，请保持插件弹窗开启；完成后助手会自动退出。',
  douyinTranscriptAdded: (count: number, device: string, elapsed: number) =>
    `已用${device}识别 ${count} 段字幕（${Math.max(1, Math.round(elapsed))} 秒）`,
  recentTags: '常用',
  addTag: '+ 标签',
  markLearned: '本篇已学习',
  diagnose: '抓取不准？生成诊断信息',
  diagnosePrivacyConfirm:
    '诊断信息会包含当前页面链接、标题、部分正文和图片地址，可能涉及私密内容。复制前请确认可以放进剪贴板，发送给别人前请先脱敏。继续生成吗？',
  diagnosing: '正在生成…',
  diagnoseCopied: '诊断信息已复制到剪贴板，发送前请先检查并脱敏',
  diagnoseFailed: '诊断生成失败',
  openSettings: '设置',
  needVault: '请先在设置里填写 Obsidian 仓库名',
  needApiKey: '请先在设置里填写 Local REST API 的 API Key',
  tooLongWarn: '内容较长，通过 obsidian:// 传递可能被截断，建议后续启用本地 API 保存',
  // popup —— 图片处理方式（与设置页同一开关，改动会同步回设置）
  imageSection: '图片',
  imageDownload: '下载到本地',
  imageReference: '引用链接',
  imageDownloadHint: '图片下载进仓库，离线也能看，会占用本地空间',
  imageReferenceHint:
    '公开图片只引用链接、不占空间；飞书等需登录的图片会自动下载到本地以保证能显示。原网页删图/失效后被引用的图将无法预览。',
  imageDownloadNeedRest: '“下载到本地”需在设置里把保存方式改为 Local REST API',
  gatedImagesUriNote:
    '（注意：部分需登录的图片如飞书无法通过链接显示，建议改用 Local REST API 保存方式）',
  // 保存图片时的进度/结果文案
  imagesSavedAll: (saved: number, total: number) => `图片 ${saved}/${total} 已保存`,
  imagesSavedGated: (saved: number, total: number) =>
    `${saved}/${total} 张需登录的图片已下载到本地（飞书等无法用链接预览），其余仍按链接引用`,
  imagesSavedFail: (err: string) => `（失败：${err}）`,
  // options
  settingsTitle: 'Nomo Clipper · 设置',
  settingsGroupImages: '图片处理',
  settingsGroupArchive: '归档与命名',
  settingsArchiveFolderMoved: '默认保存文件夹已移到每个仓库的卡片里（不同仓库各自设置）。下面是所有仓库通用的命名规则。',
  settingsGroupProps: '属性字段',
  settingsCustomFields: '自定义字段',
  settingsCustomFieldsHint: '给每篇笔记加固定属性，会写进 frontmatter。例：状态 / 未读、类型 / 文章',
  cfKey: '键',
  cfValue: '值',
  cfAdd: '+ 添加字段',
  settingsTheme: '主题',
  settingsHighlight: '高亮',
  settingsHighlightFloatingButton: '显示划词高亮浮动按钮',
  settingsHighlightFloatingHint:
    '关闭后，选中文字不会自动弹出「高亮」按钮；仍可用右键菜单或快捷键高亮选区。',
  themeAuto: '跟随系统',
  themeLight: '浅色',
  themeDark: '深色',
  settingsGroupVaults: '保存目标',
  settingsVaultsHint:
    'Obsidian 与飞书可以同时启用。下方每张卡片只负责对应目标的连接与保存位置。',
  profileVaultPlaceholder: '仓库名（如 我的笔记）',
  profileSetActive: '设为当前',
  profileActive: '当前',
  profileAdd: '+ 新建 Obsidian 仓库',
  settingsMethodUriHint: '零配置，需装 Obsidian；靠上面的"仓库名"定位仓库。不能下载图片、超长会截断。',
  settingsVaultNameHint:
    '"仓库名"= Obsidian 左下角仓库切换器里看到的名称（也是含 .obsidian 的文件夹名）。用于"链接"方式保存、以及两种方式保存后"打开"跳转——必须填对，否则打开会"未找到"。',
  settingsSaveMethod: '连接方式',
  settingsMethodUri: 'obsidian:// 链接（零配置，需装 Obsidian）',
  settingsMethodRest: 'Local REST API（更稳，超长不截断）',
  settingsMethodFeishu: '飞书知识库',
  // 保存方式可选卡片：标题 + 一行说明
  methodUriTitle: 'Obsidian 链接',
  methodUriDesc: '零配置 · 需装 Obsidian',
  methodRestTitle: 'Local REST API',
  methodRestDesc: '更稳 · 超长不截断',
  methodFeishuTitle: '飞书知识库',
  methodFeishuDesc: '上传到飞书 wiki',
  // 仓库卡片
  profileNameLabel: '名称（用于下拉显示与切换）',
  profileSetActiveFull: '设为当前仓库',
  profileDelete: '删除仓库',
  // options —— 飞书配置
  settingsFeishuGuide:
    '首次使用需要创建一个飞书企业自建应用。之后插件会以你本人身份，把剪藏内容存入你有权限的知识库。',
  settingsFeishuOpenDev: '打开飞书开放平台',
  settingsFeishuCopyScopes: '复制权限名并打开权限页',
  settingsFeishuOpenRedirectGuide: '打开安全设置',
  settingsFeishuScopes: 'offline_access、drive:file:upload、drive:drive、docs:document:import、wiki:wiki',
  settingsFeishuScopesSearch:
    'offline_access drive:file:upload drive:drive docs:document:import wiki:wiki',
  settingsFeishuScopesJson:
    '{\n  "scopes": {\n    "user": [\n      "offline_access",\n      "drive:file:upload",\n      "drive:drive",\n      "docs:document:import",\n      "wiki:wiki"\n    ]\n  }\n}',
  settingsFeishuDomain: '数据中心',
  settingsFeishuAppId: 'App ID',
  settingsFeishuAppSecret: 'App Secret',
  settingsFeishuRedirectUri: 'OAuth 重定向 URL',
  settingsFeishuPermissionSearchHint:
    '点击上方按钮会复制权限名并打开当前应用的「权限管理」。进入后点「开通权限」，把权限名粘到搜索框里选择开通；若飞书后台无法一次识别多个权限，再逐个复制上面的权限名搜索。',
  settingsFeishuRedirectHint:
    '这是当前插件自动生成的回调地址。Chrome / Edge 正式安装后会自动显示，复制到飞书开放平台「安全设置 / 重定向 URL」即可。',
  settingsFeishuOAuth: '飞书登录授权',
  settingsFeishuAuthed: '已登录授权',
  settingsFeishuUnauthed: '未登录授权',
  settingsFeishuLoadSpaces: '刷新可访问知识库',
  settingsFeishuPickSpace: '请选择知识库…',
  settingsFeishuTarget: '当前保存目录：',
  feishuRoot: '目录第一层',
  feishuPickHere: '保存到此页面下',
  feishuEnter: '展开 ▸',
  feishuNoChild: '当前目录层级没有返回可选页面。若你确认这里有内容，请刷新；仍不出现时用下方链接定位具体页面。',
  settingsRestUrl: 'Local REST API 地址',
  settingsRestUrlHint:
    '默认 http://127.0.0.1:27123（需在插件里开启「Enable Non-encrypted (HTTP) Server」）',
  settingsRestKey: 'API Key',
  settingsRestKeyHint: '在 Obsidian 的 Local REST API 插件设置里复制',
  settingsRestTest: '测试连接',
  settingsRestGuide:
    '使用前：在 Obsidian 安装并启用社区插件「Local REST API」，开启 HTTP 服务，复制 API Key 填入下方。',
  settingsImageIntro: '剪藏到笔记里的图片如何处理：',
  settingsImageDownload: '下载到本地附件',
  settingsImageDownloadHint:
    '把图片下载进仓库（自包含、离线可看），并能显示飞书等需登录的图片。仅 Local REST API 方式可用。',
  settingsImageReference: '引用原网页链接（不下载）',
  settingsImageReferenceHint:
    '公开图片保留原网页链接、Obsidian 按原规格预览、不占空间；飞书等需登录的图片会自动下载到本地（仅 REST 方式），否则无法显示。风险：原网页删除/失效/改版后，被引用的图片将无法显示。',
  settingsImageDownloadNeedRest: '“下载到本地”需把上方保存方式改为 Local REST API。',
  settingsAttachFolder: '附件文件夹',
  settingsAttachFolderHint: '图片存放位置，如 attachments',
  settingsVault: 'Obsidian 仓库名',
  settingsVaultHint: '要保存到的 Obsidian 仓库名称（区分大小写）',
  settingsFolder: '默认保存文件夹',
  settingsFolderHint: '例如 “剪藏/”，留空则存到仓库根目录',
  settingsFolderPerClip: '每篇创建独立文件夹（文章+图片放一起）',
  settingsFolderTpl: '文件夹名模板',
  settingsFolderTplHint: '变量：{{date}} 日期、{{channel}} 渠道、{{title}} 标题',
  settingsFilename: '文件名模板',
  settingsFilenameHint: '可用变量：{{title}} 标题、{{date}} 日期',
  settingsTagBlock: '标签黑名单',
  settingsTagBlockHint:
    '抓页面自带标签时，命中名单的词会被丢弃（机械过滤，逗号分隔）。例：视频教程, 课程, 教程, vlog, 日常',
  settingsAutoTags: '学习状态',
  settingsUnreadTag: '未学习显示为',
  settingsLearnedTag: '已学习显示为',
  settingsReadingTagHint:
    '会写入独立的「学习状态」frontmatter 字段（不放进 tags，避免被下游 Agent 重写关键词时冲掉）。弹窗里勾选「本篇已学习」即在两者间切换。',
  settingsSiteTags: '网站标签规则',
  settingsSiteTagsHint: '域名会匹配其全部子域名。例如 example.com / 阅读。',
  siteDomain: '域名，例如 example.com',
  siteTag: '标签，例如 PM',
  addSiteRule: '+ 添加网站规则',
  settingsFrontmatter: '写入 frontmatter 属性',
  settingsSave: '保存设置',
  settingsSaved: '设置已保存',
  fieldNames: {
    source: '来源链接 source',
    author: '作者 author',
    published: '发布日期 published',
    modified: '修改日期 modified',
    description: '描述 description',
    clipped: '剪藏日期 clipped',
    tags: '标签 tags',
  },
};
