// 兆基clipper —— 中文文案集中存放，便于未来 i18n

export const T = {
  // popup
  loading: '正在提取页面内容…',
  restrictedPage: '当前页面无法剪藏（如浏览器内置页、扩展商店、PDF 等）',
  fieldContent: '正文',
  fieldFolder: '保存文件夹',
  fieldFilename: '文件名',
  fieldVault: '目标仓库',
  saveLocation: '保存位置',
  saveTo: '保存到',
  filenameNote: '磁盘上的 .md 文件名，默认同标题（改这里不影响笔记标题）',
  properties: '属性',
  useSelection: '使用选中文字',
  useFullArticle: '使用整页正文',
  fullCapture: '完整抓取全文',
  fullCapturing: '正在滚动加载全文…',
  fullCaptureHint: '页面会自动滚动一遍，请勿操作',
  highlightsCount: (n: number) => `本页高亮 ${n} 条`,
  insertHighlights: '插入到正文',
  clearHighlights: '清除',
  wordCount: (n: number) => `约 ${n} 字`,
  save: '保存到 Obsidian',
  saving: '正在保存…',
  savedOk: '✓ 已保存',
  openInObsidian: '在 Obsidian 打开',
  closeWindow: '关闭',
  existsWarn: '⚠️ 仓库已有同名笔记，保存将覆盖',
  recentTags: '常用',
  addTag: '+ 标签',
  markLearned: '本篇已学习',
  diagnose: '🔧 抓取不准？生成诊断信息',
  diagnosing: '正在生成…',
  diagnoseCopied: '诊断信息已复制到剪贴板，请粘贴发给开发者',
  diagnoseFailed: '诊断生成失败',
  openSettings: '设置',
  needVault: '请先在设置里填写 Obsidian 仓库名',
  needApiKey: '请先在设置里填写 Local REST API 的 API Key',
  tooLongWarn: '内容较长，通过 obsidian:// 传递可能被截断，建议后续启用本地 API 保存',
  // popup —— 图片处理方式（与设置页同一开关，改动会同步回设置）
  imageSection: '图片',
  imageDownload: '📥 下载到本地',
  imageReference: '🔗 引用链接',
  imageDownloadHint: '图片下载进仓库，离线也能看，会占用本地空间',
  imageReferenceHint:
    '公开图片只引用链接、不占空间；飞书等需登录的图片会自动下载到本地以保证能显示。原网页删图/失效后被引用的图将无法预览。',
  imageDownloadNeedRest: '“下载到本地”需在设置里把保存方式改为 Local REST API',
  gatedImagesUriNote:
    '（注意：部分需登录的图片如飞书无法通过链接显示，建议改用 Local REST API 保存方式）',
  // 保存图片时的进度/结果文案
  imagesSavedAll: (saved: number, total: number) => `图片 ${saved}/${total} 已保存`,
  imagesSavedGated: (saved: number, total: number) =>
    `${saved}/${total} 张需登录的图片已下载到本地（飞书等无法用链接预览），其余仍按链接引用`,
  imagesSavedFail: (err: string) => `（失败：${err}）`,
  // options
  settingsTitle: '兆基clipper · 设置',
  settingsGroupImages: '图片处理',
  settingsGroupArchive: '归档与命名',
  settingsArchiveFolderMoved: '默认保存文件夹已移到每个仓库的卡片里（不同仓库各自设置）。下面是所有仓库通用的命名规则。',
  settingsGroupProps: '属性字段',
  settingsCustomFields: '自定义字段',
  settingsCustomFieldsHint: '给每篇笔记加固定属性，会写进 frontmatter。例：状态 / 未读、类型 / 文章',
  cfKey: '键',
  cfValue: '值',
  cfAdd: '+ 添加字段',
  settingsTheme: '主题',
  themeAuto: '跟随系统',
  themeLight: '浅色',
  themeDark: '深色',
  settingsGroupVaults: '仓库（保存目标）',
  settingsVaultsHint:
    '每个仓库一张卡片：填仓库名 + 选保存方式 +（REST 的）地址和 Key。在使用界面下拉一键切换；标「当前」的是默认用的那个。',
  profileVaultPlaceholder: '仓库名（如 我的笔记）',
  profileSetActive: '设为当前',
  profileActive: '当前 ✓',
  profileAdd: '+ 新建仓库',
  settingsMethodUriHint: '零配置，需装 Obsidian；靠上面的"仓库名"定位仓库。不能下载图片、超长会截断。',
  settingsVaultNameHint:
    '"仓库名"= Obsidian 左下角仓库切换器里看到的名称（也是含 .obsidian 的文件夹名）。用于"链接"方式保存、以及两种方式保存后"打开"跳转——必须填对，否则打开会"未找到"。',
  settingsSaveMethod: '保存方式',
  settingsMethodUri: 'obsidian:// 链接（零配置，需装 Obsidian）',
  settingsMethodRest: 'Local REST API（更稳，超长不截断）',
  settingsRestUrl: 'Local REST API 地址',
  settingsRestUrlHint:
    '默认 http://127.0.0.1:27123（需在插件里开启「Enable Non-encrypted (HTTP) Server」）',
  settingsRestKey: 'API Key',
  settingsRestKeyHint: '在 Obsidian 的 Local REST API 插件设置里复制',
  settingsRestTest: '测试连接',
  settingsRestGuide:
    '使用前：在 Obsidian 安装并启用社区插件「Local REST API」，开启 HTTP 服务，复制 API Key 填入下方。',
  settingsImageIntro: '剪藏到笔记里的图片如何处理：',
  settingsImageDownload: '下载到本地附件',
  settingsImageDownloadHint:
    '把图片下载进仓库（自包含、离线可看），并能显示飞书等需登录的图片。仅 Local REST API 方式可用。',
  settingsImageReference: '引用原网页链接（不下载）',
  settingsImageReferenceHint:
    '公开图片保留原网页链接、Obsidian 按原规格预览、不占空间；飞书等需登录的图片会自动下载到本地（仅 REST 方式），否则无法显示。风险：原网页删除/失效/改版后，被引用的图片将无法显示。',
  settingsImageDownloadNeedRest: '“下载到本地”需把上方保存方式改为 Local REST API。',
  settingsAttachFolder: '附件文件夹',
  settingsAttachFolderHint: '图片存放位置，如 attachments',
  settingsVault: 'Obsidian 仓库名',
  settingsVaultHint: '要保存到的 Obsidian 仓库名称（区分大小写）',
  settingsFolder: '默认保存文件夹',
  settingsFolderHint: '例如 “剪藏/”，留空则存到仓库根目录',
  settingsFolderPerClip: '每篇创建独立文件夹（文章+图片放一起）',
  settingsFolderTpl: '文件夹名模板',
  settingsFolderTplHint: '变量：{{date}} 日期、{{channel}} 渠道、{{title}} 标题',
  settingsFilename: '文件名模板',
  settingsFilenameHint: '可用变量：{{title}} 标题、{{date}} 日期',
  settingsTagBlock: '标签黑名单',
  settingsTagBlockHint:
    '抓页面自带标签时，命中名单的词会被丢弃（机械过滤，逗号分隔）。例：视频教程, 课程, 教程, vlog, 日常',
  settingsAutoTags: '学习状态',
  settingsUnreadTag: '未学习显示为',
  settingsLearnedTag: '已学习显示为',
  settingsReadingTagHint:
    '会写入独立的「学习状态」frontmatter 字段（不放进 tags，避免被下游 Agent 重写关键词时冲掉）。弹窗里勾选「本篇已学习」即在两者间切换。',
  settingsSiteTags: '网站标签规则',
  settingsSiteTagsHint: '域名会匹配其全部子域名。例如 woshipm.com / PM。',
  siteDomain: '域名，例如 woshipm.com',
  siteTag: '标签，例如 PM',
  addSiteRule: '+ 添加网站规则',
  settingsFrontmatter: '写入 frontmatter 属性',
  settingsSave: '保存设置',
  settingsSaved: '设置已保存',
  fieldNames: {
    source: '来源链接 source',
    author: '作者 author',
    published: '发布日期 published',
    modified: '修改日期 modified',
    description: '描述 description',
    clipped: '剪藏日期 clipped',
    tags: '标签 tags',
  },
};
