// 兆基clipper —— 中文文案集中存放，便于未来 i18n

export const T = {
  // popup
  loading: '正在提取页面内容…',
  restrictedPage: '当前页面无法剪藏（如浏览器内置页、扩展商店、PDF 等）',
  fieldContent: '正文',
  fieldFolder: '保存文件夹',
  fieldFilename: '文件名',
  fieldVault: '目标仓库',
  saveLocation: '保存位置',
  filenameNote: '磁盘上的 .md 文件名，默认同标题（改这里不影响笔记标题）',
  properties: '属性',
  useSelection: '使用选中文字',
  useFullArticle: '使用整页正文',
  fullCapture: '完整抓取全文',
  fullCapturing: '正在滚动加载全文…',
  fullCaptureHint: '页面会自动滚动一遍，请勿操作',
  highlightsCount: (n: number) => `本页高亮 ${n} 条`,
  insertHighlights: '插入到正文',
  clearHighlights: '清除',
  wordCount: (n: number) => `约 ${n} 字`,
  save: '保存到 Obsidian',
  saving: '正在保存…',
  savedOk: '✓ 已保存',
  openInObsidian: '在 Obsidian 打开',
  closeWindow: '关闭',
  existsWarn: '⚠️ 仓库已有同名笔记，保存将覆盖',
  recentTags: '常用',
  addTag: '+ 标签',
  diagnose: '🔧 抓取不准？生成诊断信息',
  diagnosing: '正在生成…',
  diagnoseCopied: '诊断信息已复制到剪贴板，请粘贴发给开发者',
  diagnoseFailed: '诊断生成失败',
  openSettings: '设置',
  needVault: '请先在设置里填写 Obsidian 仓库名',
  needApiKey: '请先在设置里填写 Local REST API 的 API Key',
  tooLongWarn: '内容较长，通过 obsidian:// 传递可能被截断，建议后续启用本地 API 保存',
  // options
  settingsTitle: '兆基clipper · 设置',
  settingsGroupImages: '本地图片',
  settingsGroupArchive: '归档与命名',
  settingsGroupProps: '属性字段',
  settingsCustomFields: '自定义字段',
  settingsCustomFieldsHint: '给每篇笔记加固定属性，会写进 frontmatter。例：状态 / 未读、类型 / 文章',
  cfKey: '键',
  cfValue: '值',
  cfAdd: '+ 添加字段',
  settingsTheme: '主题',
  themeAuto: '跟随系统',
  themeLight: '浅色',
  themeDark: '深色',
  settingsSaveMethod: '保存方式',
  settingsMethodUri: 'obsidian:// 链接（零配置，需装 Obsidian）',
  settingsMethodRest: 'Local REST API（更稳，超长不截断）',
  settingsRestUrl: 'Local REST API 地址',
  settingsRestUrlHint:
    '默认 http://127.0.0.1:27123（需在插件里开启「Enable Non-encrypted (HTTP) Server」）',
  settingsRestKey: 'API Key',
  settingsRestKeyHint: '在 Obsidian 的 Local REST API 插件设置里复制',
  settingsRestTest: '测试连接',
  settingsRestGuide:
    '使用前：在 Obsidian 安装并启用社区插件「Local REST API」，开启 HTTP 服务，复制 API Key 填入下方。',
  settingsSaveImages: '保存图片到本地附件',
  settingsSaveImagesHint:
    '剪藏时把图片下载进仓库（自包含、离线可看），并能显示飞书等需登录的图片。仅 REST 方式可用。',
  settingsAttachFolder: '附件文件夹',
  settingsAttachFolderHint: '图片存放位置，如 attachments',
  settingsVault: 'Obsidian 仓库名',
  settingsVaultHint: '要保存到的 Obsidian 仓库名称（区分大小写）',
  settingsFolder: '默认保存文件夹',
  settingsFolderHint: '例如 “剪藏/”，留空则存到仓库根目录',
  settingsFolderPerClip: '每篇创建独立文件夹（文章+图片放一起）',
  settingsFolderTpl: '文件夹名模板',
  settingsFolderTplHint: '变量：{{date}} 日期、{{channel}} 渠道、{{title}} 标题',
  settingsFilename: '文件名模板',
  settingsFilenameHint: '可用变量：{{title}} 标题、{{date}} 日期',
  settingsTagBlock: '标签黑名单',
  settingsTagBlockHint:
    '抓页面自带标签时，命中名单的词会被丢弃（机械过滤，逗号分隔）。例：视频教程, 课程, 教程, vlog, 日常',
  settingsFrontmatter: '写入 frontmatter 属性',
  settingsSave: '保存设置',
  settingsSaved: '设置已保存',
  fieldNames: {
    source: '来源链接 source',
    author: '作者 author',
    published: '发布日期 published',
    description: '描述 description',
    clipped: '剪藏日期 clipped',
    tags: '标签 tags',
  },
};
